version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "upskill-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1xt18tvnupbni"
s3_prefix = "upskill-app"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
